# Generated by Django 3.1.4 on 2023-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('url', models.TextField(blank=True, default='', max_length=200, verbose_name='目标地址')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '扫描列表',
                'verbose_name_plural': '扫描列表',
            },
        ),
    ]
