# Generated by Django 3.1.4 on 2023-03-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='scanlist',
        ),
    ]
