# Generated by Django 3.1.4 on 2023-03-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0002_auto_20230325_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='dirList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='', max_length=200, verbose_name='目标地址')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('fileway', models.TextField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition.scanlist')),
            ],
            options={
                'verbose_name': '扫描列表',
                'verbose_name_plural': '扫描列表',
            },
        ),
    ]
