# Generated by Django 3.1.4 on 2023-03-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0003_dirlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirlist',
            old_name='fileway',
            new_name='prot',
        ),
        migrations.RemoveField(
            model_name='dirlist',
            name='url',
        ),
    ]
