# Generated by Django 3.1.4 on 2023-03-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0005_auto_20230325_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='ip',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='IP地址'),
        ),
    ]
