# Generated by Django 3.1.4 on 2023-03-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0006_port_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='扫描端口'),
        ),
        migrations.CreateModel(
            name='Cmslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default='', max_length=200, verbose_name='目标地址')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('cms', models.TextField(blank=True, default='', max_length=500, verbose_name='指纹')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisition.scanlist')),
            ],
            options={
                'verbose_name': '指纹识别',
                'verbose_name_plural': '指纹识别',
            },
        ),
    ]
