# Generated by Django 3.1.4 on 2023-03-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0007_auto_20230326_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dirlist',
            options={'verbose_name': '目录扫描', 'verbose_name_plural': '目录扫描'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': '端口扫描', 'verbose_name_plural': '端口扫描'},
        ),
    ]
